# Generated by Django 4.2.10 on 2024-04-18 15:07

from django.db import migrations, models
import userauths.models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0002_userprofie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofie',
            name='cover_pic',
            field=models.ImageField(blank=True, default='cover.jpg', null=True, upload_to=userauths.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='userprofie',
            name='profile_pic',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to=userauths.models.user_directory_path),
        ),
    ]
