# Generated by Django 4.2.10 on 2024-04-18 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0003_alter_userprofie_cover_pic_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProfie',
            new_name='UserProfile',
        ),
    ]
